branches:
  - name: "release" # dummy branch

  - name: "+([0-9])?(.{+([0-9]),x}).x"
    channel: "latest"
    prerelease: "maarlab"

  - name: "main"
    channel: "latest"
    prerelease: "maarlab" # vX.Y.Z-maarlab.N

  - name: "next"
    channel: "next"
    prerelease: "maarlab-next" # vX.Y.Z-maarlab-next.N

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - "@semantic-release/github"

analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    preset: "angular"
    releaseRules:
      # Major
      - breaking: true
        release: "major"
      # Minor
      - type: "feat"
        release: "minor"
      # Patch
      - revert: true
        release: "patch"
      - type: "fix"
        release: "patch"
      - type: "perf"
        release: "patch"
      - type: "chore"
        scope: "deps"
        release: false
      - type: "docs"
        release: "patch"
      # No release
      - type: "style"
        release: false
      - type: "ci"
        release: false
      - type: "chore"
        scope: "project"
        release: false

generateNotes:
  - path: "@semantic-release/release-notes-generator"
    preset: "conventionalcommits"
    presetConfig:
      types:
        - type: "feat"
          section: "✨ Features"
          hidden: false
        - type: "fix"
          section: "🐛 Bug Fixes"
          hidden: false
        - type: "fix"
          scope: "deps"
          section: "📦‍ Dependencies"
          hidden: false
        - type: "docs"
          section: "📝 Documentation"
          hidden: false
        - type: "perf"
          section: "⚡ Performance Improvements"
          hidden: false
        - type: "chore"
          section: "🧹 Maintenance"
          hidden: false
        - type: "chore"
          scope: "project"
          hidden: true
        - type: "chore"
          scope: "deps"
          hidden: true
        - type: "revert"
          hidden: false
        - type: "ci"
          hidden: true
    writerOpts:
      commitsSort:
